<h1 style="text-align:center;">Practical-2</h1>

**1)Creating one dimension from list**

In [1]:
import numpy as np

array = np.array([1,2,3,4,5])
print("Array:\n",array)

Array:
 [1 2 3 4 5]


**2)To Create 3x3 matrix  with values ranging from 2 to 10**

In [2]:
import numpy as np

array = np.array([[2,3,4],[5,6,7],[8,9,10]])
print("Array:\n",array)

Array:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


**3)To append values at the end**

In [3]:
import numpy as np

array = np.array([1,2,3,4,5])
print("Array:\n",array)
array = np.append(array,[6,7,8])
print(array)

Array:
 [1 2 3 4 5]
[1 2 3 4 5 6 7 8]


**4)To create another shape from an array without changing its data(3x2 to 2x3)**

In [4]:
import numpy as np

array = np.array([[1,2,3],[4,5,6]])
print("Matrix 3x2:\n",array)

array = np.array([[1,2],[3,4],[5,6]])
print("Matrix 2x3:\n",array)

Matrix 3x2:
 [[1 2 3]
 [4 5 6]]
Matrix 2x3:
 [[1 2]
 [3 4]
 [5 6]]
